version: '3'

services:
  mysqldev:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass5622
      MYSQL_DATABASE: event
      MYSQL_USER: root
      MYSQL_PASSWORD: pass5622
  web:
    restart: always
    build:
     dockerfile: Dockerfile
     context: .
    container_name: java_web
    ports:
      - "8888:8080"
    stdin_open: true
    tty: true
    env_file:
      - ./db.env
    environment:
      - MY_SQL_PORT=3306
      - MY_SQL_DATABASE=event
